# -*- coding: utf-8 -*-
{
    "name": "WeighTrack",
    "version": "19.0.1.4.2",
    "category": "Operations/Inventory",
    "summary": "Weighing management for estate operations",
    "author": "PT. Hanara Prima Solusindo",
    "license": "LGPL-3",
    "depends": ["base", "mail", "stock", "hr", "product"],
    "data": [
        "security/access_groups.xml",
        "security/ir.model.access.csv",
        "data/weightrack_sequence.xml",
        "data/stock_opname_difference_reason_data.xml",
        "data/daily_stock_analysis_cron.xml",
        "views/api_views.xml",
        "views/api_request_log_views.xml",
        "views/weighing_manual_log_views.xml",
        "views/employee_role_views.xml",
        "views/product_views.xml",
        "views/customer_views.xml",
        "views/shrinkage_tolerance_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_picking_views.xml",
        "views/receipt_rule_views.xml",
        "views/weighing_views.xml",
        "views/weighing_production_report.xml",
        "views/weighing_production_report_views.xml",
        "views/weighing_production_detail_report.xml",
        "views/weighing_production_detail_report_views.xml",
        "views/tapper_production_total_report.xml",
        "views/tapper_production_total_report_views.xml",
        "views/production_summary_report.xml",
        "views/production_summary_report_views.xml",
        "views/manual_weighing_report.xml",
        "views/manual_weighing_report_views.xml",
        "views/weighing_reject_slab_report.xml",
        "views/weighing_reject_slab_report_views.xml",
        "views/storage_shrinkage_report.xml",
        "views/storage_shrinkage_report_views.xml",
        "views/stock_out_report.xml",
        "views/stock_out_report_views.xml",
        "views/shipping_report.xml",
        "views/shipping_report_views.xml",
        "views/delivery_shrinkage_report.xml",
        "views/delivery_shrinkage_report_views.xml",
        "views/daily_stock_report.xml",
        "views/daily_stock_report_views.xml",
        "views/daily_stock_analysis_views.xml",
        "views/production_slip_report.xml",
        "views/production_receipt_cancel_wizard_views.xml",
        "views/shrinkage_tolerance_override_views.xml",
        "views/production_receipt_views.xml",
        "views/estate_views.xml",
        "views/weather_views.xml",
        "views/weather_data_views.xml",
        "views/division_views.xml",
        "views/drc_views.xml",
        "views/field_views.xml",
        "views/field_production_import_wizard_views.xml",
        "views/field_production_report.xml",
        "views/field_production_report_wizard_pdf.xml",
        "views/field_production_report_wizard_views.xml",
        "views/field_production_views.xml",
        "views/weighing_location_views.xml",
        "views/foreman_views.xml",
        "views/tapper_views.xml",
        "views/device_state_reason_wizard_views.xml",
        "views/device_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_opname_difference_reason_views.xml",
        "views/stock_opname_apply_wizard_views.xml",
        "views/stock_opname_line_views.xml",
        "views/stock_opname_views.xml",
        "views/stock_opname_report.xml",
        "views/stock_movement_date_correction_views.xml",
        "views/delivery_do_wizard_views.xml",
        "views/delivery_backdate_wizard_views.xml",
        "views/delivery_customer_correction_wizard_views.xml",
        "views/delivery_received_qty_correction_wizard_views.xml",
        "views/delivery_manual_weighing_wizard_views.xml",
        "views/delivery_return_wizard_views.xml",
        "views/delivery_line_allocation_views.xml",
        "views/delivery_route_views.xml",
        "views/delivery_step_views.xml",
        "views/delivery_views.xml",
        "views/delivery_report.xml",
        "views/stock_picking_views.xml",

        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "weightrack/static/src/css/delivery.css",
            "weightrack/static/src/js/delivery_auto_save.js",
            "weightrack/static/src/js/do_lot_cancel_live.js",
        ],
    },
    "application": True,
    "installable": True,
}
