# -*- coding: utf-8 -*-
{
    "name": "WeighTrack",
    "version": "19.0.1.3.0",
    "category": "Operations/Inventory",
    "summary": "Weighing management for estate operations",
    "author": "PT. Hanara Prima Solusindo",
    "license": "LGPL-3",
    "depends": ["base", "mail", "stock", "hr", "product"],
    "data": [
        "security/access_groups.xml",
        "security/ir.model.access.csv",
        "data/weighing_sequence.xml",
        "views/api_views.xml",
        "views/api_request_log_views.xml",
        "views/employee_role_views.xml",
        "views/product_views.xml",
        "views/shrinkage_tolerance_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_picking_views.xml",
        "views/receipt_rule_views.xml",
        "views/weighing_views.xml",
        "views/production_slip_report.xml",
        "views/production_receipt_cancel_wizard_views.xml",
        "views/production_receipt_views.xml",
        "views/estate_views.xml",
        "views/weather_views.xml",
        "views/weather_data_views.xml",
        "views/division_views.xml",
        "views/weighing_location_views.xml",
        "views/foreman_views.xml",
        "views/tapper_views.xml",
        "views/device_state_reason_wizard_views.xml",
        "views/device_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_opname_difference_reason_views.xml",
        "views/stock_opname_apply_wizard_views.xml",
        "views/stock_opname_line_views.xml",
        "views/stock_opname_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
