# -*- coding: utf-8 -*-
{
    "name": "WeighTrack",
    "version": "19.0.1.0.0",
    "category": "Operations/Inventory",
    "summary": "Weighing management for estate operations",
    "author": "PT. Hanara Prima Solusindo",
    "license": "LGPL-3",
    "depends": ["base", "mail", "stock", "hr"],
    "data": [
        "security/access_groups.xml",
        "security/ir.model.access.csv",
        "views/api_config_views.xml",
        "views/api_request_log_views.xml",
        "views/employee_role_mapping_views.xml",
        "views/estate_views.xml",
        "views/division_views.xml",
        "views/weighing_location_views.xml",
        "views/foreman_views.xml",
        "views/tapper_views.xml",
        "views/device_state_reason_wizard_views.xml",
        "views/device_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
